version: "3.7"
services:
  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     argTest: success
    image: chenhung0506/resume:${TAG}
    container_name: resume
    # environment:
    #   - PORT=22222
    volumes:
      - ~/volumes/resume:/usr/src/app/logs
    restart: always
    # deploy:
    #   resources:
    #     mem_limit: 5125m
    # depends_on: 
    #   - nlu-tde
    ports: 
      - "${PORT}:${PORT}"
    env_file:
      - dev.env
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:${PORT}/healthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # networks:
    #   - docker-compose-base_default