version: '3.9'
services:
  resume:
    build:
      context: .
      dockerfile: Dockerfile
    image: harbor.linch.live/react/resume:latest
    ports:
      - "3006:80"
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
