version: "3.7"
services:
  web:
    image: harbor.chlin.tk/vue/resume:${TAG}
    container_name: resume
    volumes:
      - ~/volumes/resume:/usr/src/app/logs
    ports: 
      - "${PORT}:${PORT}"
    env_file:
      - dev.env
    # healthcheck:
      # test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/healthCheck || exit 1"]
      # interval: 600s
      # timeout: 10s
      # start_period: 10s
      # retries: 3
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx